### ISSUE TITLE
Do Node iterations multithread?

### ISSUE THREAD

**Issue by TheChymera** [nipy/nipype#1101]
If I have a node for file conversion or realignement etc, and I make it iterable, so that I can go through multiple files in one go:

Is the node smart enough to automatically parallelize this? If not, is there any clean-ish way to make my workflow multithread at least where iterations of the same node are concerned?

**Comment by mwaskom** [comment]
Do you mean `Node` or `MapNode`?

**Comment by TheChymera** [comment]
I think I mean `Node`, as I have never dealt with the latter before.

**Comment by mwaskom** [comment]
Then I'm not sure what you mean, thought it looks like you intended to include some code in the original question but it didn't make it through.

**Comment by mwaskom** [comment]
You might also want to read through my [tutorial notebook](http://nbviewer.ipython.org/github/mwaskom/nipype_concepts/blob/master/iteration.ipynb) on iteration using `iterables` and `MapNode`.

**Comment by TheChymera** [comment]
What I mean is: will or can ´Node´ instances that are made iterable (via `Node.iterables`) multithread?

**Comment by mwaskom** [comment]
Yes, that is very much the point of `iterables`.

**Comment by satra** [comment]
@TheChymera - to add to mike's comment - to get the embarassing parallelism you have to run with a non-linear plugin like MultiProc or a cluster plugin like SGE/PBS/SLURM

**Comment by mwaskom** [comment]
Oh right; good point :)

**Comment by mwaskom** [comment]
Actually just to clarify, I assumed you're using "multithread" casually, but it's more accurate to say that the process will run in *parallel*, but it won't actually multithreading in the traditional sense.

**Comment by TheChymera** [comment]
So basically this means that an iterable node will run faster on a multi-core system than just a `for` loop, yes?

@satra why
> embarassing 

?

Also, is there any downside to using e.g. `workflow.run(plugin=’SLURM’)` with all my workflows? How can I decide which of those plug-ins to use? Will multithreading be completely disabled if I do not specify a plug-in when I run the workflow?

**Comment by mwaskom** [comment]
So basically this means that an iterable node will run faster on a multi-core system than just a for loop, yes?

Yes. If you try the tutorial notebook I linked you to, it has a self-contained simple workflow that demonstrates this.

> @satra why "embarassing"?

This is a [specific term](http://en.wikipedia.org/wiki/Embarrassingly_parallel) for certain parallel computing problems, like the kinds that can handled by iterables.

> Also, is there any downside to using e.g. workflow.run(plugin=’SLURM’) with all my workflows? How can I decide which of those plug-ins to use? Will multithreading be completely disabled if I do not specify a plug-in when I run the workflow?

Well, if you don't have slurm installed, it won't work :). But there is some overhead involved in submitting a slurm job (same is true for the other managed execution plugins like SGE and Torque), so if there isn't anything to parallelize than a workflow executed in serial with the `Linear` plugin will probably run a bit faster (though the difference is likely not to be large relative to the computation time).

The default behavior (i.e. what happens if you just call `workflow.run()` is controlled through the [config file](http://nipy.sourceforge.net/nipype/users/config_file.html#execution). The default default is to use the `Linear` plugin, i.e. each step in the workflow is executed locally in serial.

**Comment by TheChymera** [comment]
@mwaskom so, to summarize: plug-ins like `SLURM` etc. can help nipype parallelize the *entire* workflow. But iterated nodes will still run in paralell, regardless - just that the different Nodes will be executed sequentially if I do not specify a plug-in other than `Linear`.

Did I understand this correctly?

**Comment by mwaskom** [comment]
No, I think there is still confusion.

Using `Node.iterables` is *how* you "parallelize the entire workflow", there's no distinction there. The [docs](http://nipy.sourceforge.net/nipype/users/mapnode_and_iterables.html) have some nice images that might make this more clear.

What you are saying about parallelizing a single node is much closer to what `MapNode` does (also covered on that docs page and in the tutorial I linked above). However, in either case, there will be no automatic parallelization unless you specify a parallel workflow plugin.

**Comment by TheChymera** [comment]
Ok, many thanks for clarifying this!

So to get any paralellization at all, I will need either SLURM, or PBS, or SCE, or MultiProc in my workflow.

(ATM) I am trying to do this on a normal desktop computer (4 cores, with multithreading), though I am also setting up a virtual machine on a cluster (32 cores for the machine) - which plug-in would be recommended for each of those cases?

**Comment by satra** [comment]
`MultiProc` - but post debugging on a working workflow - always debug your workflow with `Linear` and with `iterables` set to singleton lists if you have `iterables`.

**Comment by TheChymera** [comment]
Ok, I think this answers my question, and thank you very much for the clarification!
