### ISSUE TITLE
Store provenance in NIFTI files using niprov

### ISSUE THREAD

**Issue by chrisfilo** [nipy/nipype#1111]
NIprov https://github.com/ilogue/niprov is a library for storing provenance for neuroimaging analyses. We should consider tweaking Nipype to automatically save the provenance in the NIFTI files produced in each step. This would be incredibly useful! @satra @ilogue

**Comment by ilogue** [comment]
I'd love to help with this. Let me know what you guys need.

**Comment by satra** [comment]
hey jasper, what would it take to make niprov w3c compliant? since nipype itself has a provenance generator, i'm less inclined to adopt niprov to replace it. however, i'm happy to use to provide richer details, etc.,. since nipype's provenance tracker is quite basic.

regarding embedding provenance into nifti files, i'm willing to embed an external prov link, but i think it's a little silly to embed the same provenance into every 3d file that gets generated, when that happens. i have always said that it is the provenance that is the information or data flow, and the files are pieces of the provenance graph. i'd like to continue thinking that way.

**Comment by inati** [comment]
Be careful that every package that uses the nifti meta data does it differently and that there is no guarantee that your embedding of provenance will survive a processing step.

**Comment by ilogue** [comment]
Which w3c standard did you have in mind Satra? That would be a great thing.

Niprov optionally stores provenance for the file in question in the nifti
file header, but I'm more focused on the central (mongodb) storage. One of
the reasons for this is what Souheil mentions.

**Comment by ilogue** [comment]
Also, I made a niprov integration piece for the python mne package, I
imagine I could do the same for nipype.

**Comment by satra** [comment]
[w3c prov](http://www.w3.org/TR/prov-overview/)

the latest version that nipype implements is in this PR #1279 (see the provenance.py file, as well as pipeline/utils.py).

**Comment by ilogue** [comment]
Okay I have implemented some support for exporting to W3C PROV xml in niprov. It's a work in progress (see https://github.com/ilogue/niprov/issues/71) but the basics for one image are there.

Also you can now configure niprov to attach the provenance to a file header with:
```
attach = xml
```
in the `~/niprov.cfg` configuration file or in python code. Other formats include e.g. `json` and `narrated`. This works for nifti and fif (the mne format).

Other ways of exporting include to a text file or on the commandline:
```
provenance export -f xml
```
I ended up not using the python prov library, as it depends on the binary lxml package.

Let me know what you think!

**Comment by djarecka** [comment]
@satra @chrisfilo any new comments? is it still an issue?

**Comment by satra** [comment]
we have gone back and forth on whether to store provenance in files. given the work on pynidm, i would like to focus on that. in the longer term i think provenance will be outside a file with a relatively easy option to get provenance of files from a given registered file.
