### ISSUE TITLE
Add quotes to file paths

### ISSUE THREAD

**Issue by alexsavio** [nipy/nipype#1283]
In fsl.MultiImageMaths the file paths are unquoted. If an absolute path has white spaces, this would throw an error from the command line, right?
https://github.com/nipy/nipype/blob/master/nipype%2Finterfaces%2Ffsl%2Fmaths.py#L24

**Comment by blakedewey** [comment]
This is correct. Although normally in Python you can get around this by using the "subprocess" package with "shell=False". This then takes a list of arguments and joins them together using spaces, but also escapes any other spaces it finds in your arguments. In Nipype, it seems we use "shell=True", which expects you to do the escaping/joining and just give it a string. I don't know the history of this unfortunately, maybe @satra can give more context.

**Comment by alexsavio** [comment]
I also found that all the the interfaces for ANTs have the same issue. I was adding the quotes to the file path parameters but wanted to ask here first how is the best way to fix this.

**Comment by satra** [comment]
@alexsavio - we would have to fix a few things in commandline interface to allow using shell=False. some complications arise because we essentially are processing each input, so we can turn each input into a list element, but what we may need is to also turn subcomponents into a list element.

there is an intentional space between `to` and `o`
```
-o /path/to o/outfile
```

vs

```
--o=/path/to o/outfile
```

@blakedewey - does `shell=False` handle both of the above cases well?

**Comment by blakedewey** [comment]
I am pretty sure there is not a mechanism to do the second case. As far as I know, the subprocess module takes the arguments and escapes them, then feeds them directly into the command (the first argument). The second case would end up as `--o=/path/to\ o/outfile` if you fed in `['--o=/path/to/ o/outfile']` to `Popen`, `--o /path/to o/outfile` if `['--o', ' /path/to/', 'o/outfile']` was passed.

**Comment by alexsavio** [comment]
I was suggesting to add quotes to the file paths, not using `shell=False`.

I guess that if we decide to move to `shell=False` we would have to come up with a way to split the command string into a list or directly build the list, instead of a string, from the specific interface class (or some class in the middle between Command and the interface).

In any case, adding quotes to the file paths does a lot to help `shlex.split`:
```
In [19]: shlex.split('echo --i="in file" -o "out file" --l "mask file"')
Out[19]: ['echo', '--i=in file', '-o', 'out file', '--l', 'mask file']

In [20]: shlex.split('echo --i=in file -o out file --l mask file')
Out[20]: ['echo', '--i=in', 'file', '-o', 'out', 'file', '--l', 'mask', 'file']
```

**Comment by cgc** [comment]
I just ran into this error with `fslreorient2std`. If a solution like "add quotes to inputs that are files in `CommandLine._format_arg`" is viable/sensible, I'd be open to writing that change. Otherwise, I think it would be helpful for nipype to throw an error or have a warning for files with spaces that are supplied as arguments to a CommandLine node.

**Comment by jdalrymple** [comment]
Running into this issue with the ReconAll function as well. Specifically the setting of the T1_files section where its a string variable of a path with a space in it.
