### ISSUE TITLE
IPython plugin is too slow

### ISSUE THREAD

**Issue by dpaniukov** [nipy/nipype#1568]
Hello all,

I setup ipyparallel with `conda install ipyparallel` on the latest Anaconda for Ubuntu. 
I have only 2 CPUs on my machine, so I also start ipcluster as  `ipcluster start --n 2`

My code imports subject data and does fast computation of an .nii image. At the end of the code I have `outgraph = wf.run(plugin='IPython', plugin_args={'n_procs' : 2})`.
The execution takes more than 5 minutes with little CPU activity in between spikes. 

`outgraph = wf.run(plugin='MultiProc', plugin_args={'n_procs' : 2})` or just `outgraph = wf.run()` takes less than 15 seconds. 

How do I speed up IPython execution? 
Thanks,
Dmitrii

**Comment by satra** [comment]
@dpaniukov - the default workflow configuration for nipype sleeps for 60s between parallel streams of jobs. this is default because most people end up using the workflow script on a cluster.

try setting the following config option before calling wf.run():

`wf.config['execution']['poll_sleep_duration'] = 2`

**Comment by satra** [comment]
all config options are available here: http://nipype.readthedocs.io/en/latest/users/config_file.html

**Comment by dpaniukov** [comment]
It works, thank you so much for the explanations! I'll be running this on a small ipython cluster at a lab I work for, so I do not have to give it all 60 seconds between the streams. At least for now.
