### ISSUE TITLE
Not applicable warning from input checking

### ISSUE THREAD

**Issue by gciccarelli3** [nipy/nipype#1836]
### Summary
Inappropriate warning is given about missing input when the input is actually present.  This causes significant confusion about what inputs are actually being passed into the node.

### Actual behavior
lib/python2.7/site-packages/nipype/interfaces/base.py:431: UserWarning: Input surface_fwhm requires inputs: reg_file
  warn(msg)

### Expected behavior
No warning should be printed.  The warning occurs because the smooth.inputs.reg_file is added after the smooth.inputs.surface_fwhm = val is set.

The input interface: https://github.com/nipy/nipype/blob/master/nipype/interfaces/freesurfer/preprocess.py#L1170
checks for the reg_file when surface_fwhm is given, not after all inputs have been given to the node and the node is ready to execute.

### How to replicate the behavior
--- No warning--
smooth.inputs.reg_file = 'reg.dat'
smooth.inputs.surface_fwhm = 6
-- Warning --
smooth.inputs.surface_fwhm = 6
smooth.inputs.reg_file = 'reg.dat'
https://github.com/nipy/nipype/blob/master/nipype/interfaces/freesurfer/preprocess.py#L1170

### Platform details:
please paste the output of: `python -c "import nipype; print(nipype.get_info()); print(nipype.__version__)"`
Command crashes with backports error:  backports.configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: u'%h'

**Comment by mgxd** [comment]
This warning happens to remind users if they intend to use `surface_fwhm`, `reg_file` must be provided. Since the checking is currently happening through traits as inputs are assigned, presence of the warning is strictly due to which is connected first. Generally, it's good practice to set connect statements in this order.

This can be patched by dropping the `requires` trait keyword and instead adding a `_format_arg` to Smooth's interface
