### ISSUE TITLE
[TST] [CircleCI] BBRegister autotest failing if make specs run with no FS/FS<6

### ISSUE THREAD

**Issue by mgxd** [nipy/nipype#1883]
### Summary
After running `make specs`, `test_auto_BBRegister.py` adds in argument `init` as mandatory, probably due to the inputspec for FS6. This causes circleci to fail when running `nipype.test()`
### Actual behavior
```
        for key, metadata in list(input_map.items()):

            for metakey, value in list(metadata.items()):

>               assert getattr(inputs.traits()[key], metakey) == value

E               assert None == True

E                +  where None = getattr(<traits.traits.CTrait object at 0x7f5cf44d4310>, 'mandatory')



../../interfaces/freesurfer/tests/test_auto_BBRegister.py:60: AssertionError
```
### Expected behavior
Passing
### How to replicate the behavior
- make specs, run circle tests (was happening in #1875)
However, working fine when I run `nipype.test()` local with py3.5.2 with no version of FS installed.

related #1817

**Comment by effigies** [comment]
Running `make specs` on a machine without FS or with FS6 should both result in no `mandatory` flag. The test to use the FS5.3 (with mandatory `--init-*`) is [`FSVersion and LooseVersion(FSVersion) < LooseVersion("6.0.0")`](https://github.com/nipy/nipype/blob/master/nipype/interfaces/freesurfer/preprocess.py#L1069-L1070).

So it looks like it's being run on a system with FS5.3 installed, which is odd, since the Dockerfile indicates FS6 is being installed.

**Comment by mgxd** [comment]
@effigies perhaps a non-auto test would be better for this interface, and we can skip the auto test generation. Otherwise, not having Freesurfer6 installed would cause conflicting tests every time `make specs` is run. Let me know what you think? @satra

**Comment by effigies** [comment]
What sort of functionality should be tested in order to make a regular test as valuable as the auto tests?

**Comment by mgxd** [comment]
Essentially, it will be very similar to the auto-test (mandatory args, defaults, xor, args with dependencies, etc), there are already some manual tests included [here](https://github.com/mgxd/nipype/blob/da1bd763078770f0850c7d50cb26fb45eb70a408/nipype/interfaces/freesurfer/tests/test_preprocess.py).
