### ISSUE TITLE
DISPLAY variable should be optional

### ISSUE THREAD

**Issue by satra** [nipy/nipype#2055]
### Summary

DISPLAY variable is always set to :1 when running a command line interface. There is currently now way to unset this variable

### Actual behavior

DISPLAY=:1 by default

### Expected behavior
Option to remove DISPLAY or any other environment variable.

### Platform details:

{'pkg_path': '/software/nipy-repo/nipype/nipype', 'commit_source': 'repository', 'commit_hash': 'acb37ce18', 'nipype_version': '1.0.0-gacb37ce18.dev', 'sys_version': '3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 13:19:00) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]', 'sys_executable': '/software/miniconda3/envs/dev36pype/bin/python', 'sys_platform': 'darwin', 'numpy_version': '1.12.0', 'scipy_version': '0.18.1', 'networkx_version': '1.11', 'nibabel_version': '2.1.0', 'traits_version': '4.6.0'}
1.0.0-gacb37ce18.dev

### Execution environment

Choose one
- My python environment inside container [Base Tag: nipy/mindboggle]

**Comment by oesteban** [comment]
Is it :1 because of this -> https://github.com/nipy/nipype/blob/70b2084eea746f212dbb15aa57b63325c9a99666/nipype/utils/config.py#L47 ?

We could/should address #1400 and #1403 with this one.

In general, we should read `$DISPLAY` from the system. That would let the advanced users define complex environments, and still work well in most of the cases without touching anything.

Then, the runner would take care of those interfaces with `_redirect_x = True`:

- If the runner is about to process a workflow: check if any node has the property `_redirect_x = True` and open an `Xvfb` display if no default `$DISPLAY` is set. If there is a `$DISPLAY`, we assume the machine is not headless or the user set up an VNC server.
- If the interfaces are being run isolated (not in a workflow), then the same, but opening an `Xvfb` display per interface run.

Another option is totally removing `xvfb` and give support users to manually open a virtual display when they try to run interfaces that use the x server. We touched base on this in #1819.

WDYT?

**Comment by satra** [comment]
@oesteban - it's `:1` because of that line and this: https://github.com/nipy/nipype/blob/master/nipype/interfaces/base.py#L1697

regarding your suggestions, yes we should do this all in the base-interface runner.

- we do need to figure out and make consistent how environment variables are handled. i think i prefer read and override, but we also need some syntax for deleting variables, or keeping only a few.
- since we may be doing this through runner, we should also consider the process behind running singularity/docker containers for a given interface.
- we need to take care of xvfb issues (single xvfb in a given host, ensure xvfb exits cleanly, and perhaps the manual option). 

i'd like to focus on the traitlets PR and get that done first and then turn attention to restructuring. 

the reason i ran into this issue is because vtk loads different libraries depending on whether the DISPLAY variable is set or not.

**Comment by oesteban** [comment]
I see, it makes sense fixing the DISPLAY and after traits address the xvfb issue. :+1:
