### ISSUE TITLE
Failing function nodes don't stop children to execute if run_without_submitting and MultiProc are used

### ISSUE THREAD

**Issue by chrisfilo** [nipy/nipype#2072]
See https://github.com/poldracklab/fmriprep/issues/553 for details and code to replicate the issue.

**Comment by satra** [comment]
@chrisfilo - could you please reduce this to a two node function example that we can add a test for?

**Comment by satra** [comment]
this is the code for run_without_submitting, and off the top i don't see why this wouldn't work:

https://github.com/nipy/nipype/blob/master/nipype/pipeline/plugins/base.py#L411

since it catches any exception and runs clean_queue, which is where dependencies would be removed. it would be super helpful to have a minimal example.

**Comment by chrisfilo** [comment]
I'll try to deliver a simple example. The interaction might turn out more
complex than I described.

In context of FMRIPREP disabling run_without_submitting "solved" the issue.

**Comment by mgxd** [comment]
feel free to open this again if you have a simple example
