### ISSUE TITLE
Nodes without inputs/outputs ?

### ISSUE THREAD

**Issue by rattar1989** [nipy/nipype#2088]
### Summary
I'm creating a workflow containing 9 nodes (modules) to segment MR images at different time points and then analyses the segmented area with some specific functions. Almost all my codes are written in Matlab and I use nipype wrappers so as to use them in my workflow. 

The workflow reads a path of an image folder from the database and make a copy of that folder somewhere (temporary) and apply each node of the workflow one by one on the copied image image folder.

considering this, can I define my nodes without having input/output?
Is it a right way of designing my workflow? If it's not could you please let me know what I should do?

(all my modules (nodes) are applied on each image folder sequentially and do not pass information to each other).

**Comment by effigies** [comment]
Nipype sequences by determining which nodes pass their outputs into which nodes' inputs. If you have a workflow of a bundle of nodes with no dependencies, there's no straightforward way to select an order of running.

However, you can do:

```Python
node1 = pe.Node(...)
node2 = pe.Node(...)
...

node1.run()
node2.run()
...
```

(You also don't have to use `Node`s. You can just run the interfaces directly.)

**Comment by rattar1989** [comment]
Thanks @effigies, 
how can I then run the whole pipeline in a parallel mode? (i.e. each subject file can be read from the database in parallel and go through the pipeline)

**Comment by effigies** [comment]
If possible, I would consider actually exposing inputs and outputs and connecting them so that the workflow can be ordered; if the actions need to be run sequentially, then there should be prerequisites and products of each step.

Failing that, you could do something like this:

```Python
wf1 = pe.Workflow(name='wf1')
wf2 = pe.Workflow(name='wf2')
...

for subject in subjects:
    node1 = pe.Node(...)
    node2 = pe.Node(...)
    ...
    wf1.add_nodes([node1])
    wf2.add_nodes([node2])

wf1.run(plugin='MultiProc')
wf2.run(plugin='MultiProc')
...
```

That will run the first step on all subjects in parallel, and then, when that's finished, run the second step on all subjects in parallel.

In contrast, if you have at least some kind of inputs and outputs (it could be a dummy value that has nothing to do with your processing pipeline, really), you could do the following:

```Python
wf = pe.Workflow(name='wf')
for subject in subjects:
    node1 = pe.Node(...)
    node2 = pe.Node(...)
    node3 = pe.Node(...)
    ...

    wf.connect([
        (node1, node2, [('out', 'in')]),
        (node2, node3, [('out', 'in')]),
        ...
        ])

wf.run('MultiProc')
```

This will run as many nodes in parallel that it can, as long as their prerequisites have been run.

**Comment by rattar1989** [comment]
@effigies thanks for your clear explanation. I would prefer to work on the second option as the first one would not be efficient on large population studies.
