### ISSUE TITLE
Raise exception if BIDSDataGrabber is imported using Python 2

### ISSUE THREAD

**Issue by adelavega** [nipy/nipype#2207]
Pybids no longer supports Python 2. Thus, BIDSDataGrabber should only be importable with Python 3, and raise an exception otherwise.

**Comment by adelavega** [comment]
I'd assign myself but I can't ;)

**Comment by oesteban** [comment]
I'd also include here setting the appropriate skips on tests:
  - [ ] Because Python 2
  - [ ] Because pybids was not installed in editable mode (very likely in user settings).

**Comment by adelavega** [comment]
Cool. Looks like Python 2 support might continue enough to the point that perhaps raise an Exception is a bit heavy, but it probably makes sense to skip on tests either way unless pybids CI adds back official python 2 support.

**Comment by effigies** [comment]
Is this actually a problem? Does BIDSDataGrabber depend on behavior since pybids dropped Python 2 support?

If not, can we set the Python 2 docker image to use the last Py2-compatible release tag?

So this:

https://github.com/nipy/nipype/blob/master/Dockerfile#L90-L91

Becomes

```Dockerfile
RUN curl -sSL https://github.com/INCF/pybids/archive/$TAG.tar.gz | tar xvz &&
    cd pybids && python setup.py develop
```

And you can set TAG to `0.3.0` for Py2, or `master` for current behavior.
