### ISSUE TITLE
Release of current version

### ISSUE THREAD

**Issue by TimVanMourik** [nipy/nipype#2234]
@chrisfilo @satra 
Hi Developers! Might it be an idea to release a new version of Nipype? The current version at the time of writing is nipype 0.13.1, from May 2017. Specifically, many examples that we made for [Porcupine](https://timvanmourik.github.io/Porcupine) leverage the master version of the S3DataGrabber, in order to automatically pull [openneuro](https://openneuro.org) buckets from Amazon. It would be a great help if this becomes available in the 'pip install nipype' version.

**Comment by chrisfilo** [comment]
Sounds good to me but @satra is more on top of things.

**Comment by satra** [comment]
i'm thinking a 0.14 release rather than 1.0 - i would like to see traitlets in 1.0.

a few pending things:

- [ ] fix prov issue with nipype
- [ ] review recent PRs and make sure they are included in the release.

but we could do a pre-release like an rc1 and then people should be able to install with `pip install --pre nipype` - note that this will install pre releases of all dependencies as well.

let's aim for a formal release in two weeks. @mgxd - could you please take the lead on this?

**Comment by effigies** [comment]
:+1: on 0.14

As a policy, could we set a 2 month feature release cycle, such that if traitlets isn't ready by December, we do 0.15 then?

**Comment by oesteban** [comment]
@satra, could you link to the specific issues you have in your list for those pending things before 0.14?

**Comment by mgxd** [comment]
@TimVanMourik you should be able to download the pre-release with `pip install nipype --pre`, the full release will be coming as soon as a few missing pieces are merged

**Comment by TimVanMourik** [comment]
Thanks! I'm definitely gonna try it this week 👍
