### ISSUE TITLE
I am currently using the latest version of nipype and am running into the following error:

### ISSUE THREAD

**Issue by meenakshik1993** [nipy/nipype#2402]
I am currently using the latest version of nipype and ran into the following error message. Any ideas why? 

Version of nipype found in /usr/local/bin/miniconda/envs/cpac/lib/python2.7/site-packages/nipype does not contain the MultiProc plugin. Please check installation is the most up-to-date or download and install the FCP-INDI nipype repo at https:/github.com/fcp-indi/nipype.
Error: No module named callback_log
180125-12:14:49,288 workflow INFO:
	 Workflow resting_preproc_50002_followup_1 settings: ['check', 'execution', 'logging', 'monitoring']
Could not complete cpac run for subject: 50002!
Error: Execution graph does not have a unique set of node names. Please rerun the workflow

Any help would be really appreciated!

**Comment by oesteban** [comment]
It seems that CPAC has not transitioned yet to the latest versions of nipype.

For that reason, they recommend installing nipype from their repository: https:/github.com/fcp-indi/nipype

Since I see you have a specific environment for cpac, I would recommend doing so:

```
pip uninstall nipype
pip install git+https://github.com/FCP-INDI/nipype.git
```

Please note that this will pin your nipype installation to the specific version they are maintaining in their repo.

**Comment by oesteban** [comment]
Since this problem is specific to CPAC, please follow up in FCP-INDI/C-PAC#749
