### ISSUE TITLE
Insert lazy lag in File traits with exists=True

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#2573]
### Summary

Due to NFS latency, some times users run into the `The trait <trait> of a <node> instance is an existing file name, but the path <path> does not exist`

### Actual behavior

Nipype crashes

### Expected behavior
Nipype waits for the file to be written

### How to replicate the behavior
Hard, but with a very slow NFS system it should be possible.

### Script/Workflow details
FMRIPREP

### Platform details, Execution environment:
FMRIPREP 1.0.10, singularity image.

### Solution proposed
Tweak the `File` trait and add a second checkpoint for the case when the file is being written.

**Comment by satra** [comment]
the problem is that it's not just a `File` trait, it could be a results file too:

https://github.com/nipy/nipype/blob/master/nipype/pipeline/plugins/base.py#L468

we made the assumption that if the results file can be read, then the other files are also available. probably not a great assumption, but it seems to work in most cases.

the implementation, does try to read and only extends jobs when it cannot read. so this does not apply to every job, only when the result file needs to be read.

having said all that, i think this can be cleaned up and the place where this should go is perhaps in get_inputs in the Node.
