### ISSUE TITLE
[BUG] FreeSurfer version returns None

### ISSUE THREAD

**Issue by oesteban** [nipy/nipype#2655]
### Summary

```Python
>>> from nipype.interfaces.freesurfer import ReconAll
>>> ReconAll().version is None
True
>>> from nipype.interfaces.fsl import BET
>>> BET().version
'5.0.9'
```
### Expected behavior
```Python
>>> from nipype.interfaces.freesurfer import ReconAll
>>> ReconAll().version is None
False
```

### Environment
FMRIPREP containers and pip installed environment.

**Comment by satra** [comment]
@oesteban - does the freesurfer installation contain the build-stamp.txt file?

**Comment by oesteban** [comment]
```
cat /opt/freesurfer/build-stamp.txt
freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a
```

**Comment by oesteban** [comment]
However:

```Python
>>> from nipype.interfaces.freesurfer import Info
>>> Info().version_file
'/opt/freesurfer/build-stamp.txt'
>>> Info().version()
'freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a'
>>> Info().looseversion()
LooseVersion ('6.0.1')
```

**Comment by effigies** [comment]
The issue is that `ReconAll` is a `CommandLine`, not an `FSCommand`:

https://github.com/nipy/nipype/blob/1ffe23d2b82b6fefa9fa92e59e86437591041081/nipype/interfaces/freesurfer/preprocess.py#L880

They each do separate hackery around subject dirs, and it's not clear to me we can simply re-subclass from `FSCommand`. We could always just copy the `version` bits from `FSCommand`.

**Comment by satra** [comment]
easiest may be to overwrite `version` property in `ReconAll` to use `FS.Info()`

**Comment by effigies** [comment]
@oesteban Do you need this in 1.1.1?

**Comment by effigies** [comment]
Never mind. It was a 3 second fix. Can you verify it solves your problem, and we can merge it before the release?
