### ISSUE TITLE
MRtrix 3.0 `dwi2fod` single output error

### ISSUE THREAD

**Issue by jguillon** [nipy/nipype#2822]
Hi, I got this error when executing `mrtrix3.EstimateFOD` interface with the latest MRtrix version (`3.0_RC2-117-gf098f097`) installed on macOS Mojave 10.14.2 through a `brew install mrtrix3`:

```
dwi2fod: [ERROR] CSD algorithm expects a single input response function and single output FOD image
```

It seems that MRtrix now expects "pairs of input tissue response and output ODF images" according to [the documentation](https://mrtrix.readthedocs.io/en/latest/reference/commands/dwi2fod.html#usage). So I guess that the following lines need to be updated:

https://github.com/nipy/nipype/blob/35b58cdb59a900430f4b9639e220c8408341805d/nipype/interfaces/mrtrix3/reconst.py#L95-L109

**Comment by matteomancini** [comment]
The issue is that `dwi2fod` needs to be able to handle both CSD (where the only output is the white matter FOD) and multi-tissue CSD (where there is one file for each tissue). To solve the issue, `gm_odf` and `csf_odf` need to have the `useDefault` field equal to `False`. I have tested the solution and it works, I already fixed the code in [my own fork of Nipype](https://github.com/matteomancini/nipype/tree/mrtrix3-usedefault-issue), if it is ok I can make a pull request. A related issue that I fixed there is the `useDefault=True` for the `max_sh` argument for `mrtrix3.EstimateFOD`, which causes troubles for multi-shell data. I already run the `make check-before-commit` and the code I worked on is fine.

**Comment by effigies** [comment]
Hi @jguillon, sorry for how long this took. The 1.5.0 release will have a `ConstrainedSphericalDeconvolution` interface that should work correctly. In case you didn't see other discussion, the concern with fixing `EstimateFOD` is that people using `msmt_csd` may have been depending on the bug in their workflows.

The new interface is identical, but without the bug.
