### ISSUE TITLE
Config file missing from docs

### ISSUE THREAD

**Issue by effigies** [nipy/nipype#3198]
This is no longer being rendered in the same place, and I can't find another place it's linked from: https://nipype.readthedocs.io/en/0.12.1/users/config_file.html

**Comment by satra** [comment]
it lives here: https://miykael.github.io/nipype_tutorial/notebooks/basic_execution_configuration.html

**Comment by oesteban** [comment]
Yup, @satra, I find that super-confusing. I think adding a link somewhere and updating https://nipype.readthedocs.io/en/0.12.1/users/config_file.html to point to the tutorials would be great.

**Comment by satra** [comment]
@oesteban - are you saying this is insufficient: https://nipype.readthedocs.io/en/latest/examples.html
the tutorials are also pointed at by the quickstart page.

there was a decision taken a while back to move all of the user oriented docs to the tutorials. the link that is being pointed to is 0.12.1, which clearly states its not the latest version (and is several versions old).  i don't think we should be altering that specific version anymore. the note at the top of the page i think is autogenerated by readthedocs, which is why it goes to a page not found.

i can't control google's indexing, but the config page of the tutorial does show up on an anonymous search.

**Comment by oesteban** [comment]
> i can't control google's indexing, but the config page of the tutorial does show up on an anonymous search.

Ha, I got this before your reading your final comment:
<img width="847" alt="Screen Shot 2020-04-01 at 5 39 05 PM" src="https://user-images.githubusercontent.com/598470/78199230-e7445c00-743f-11ea-92c9-cba2a8a39e03.png">
The two first links lead to https://nipype.readthedocs.io/en/1.1.0/users/config_file.html or older versions. We should have something for latest under https://nipype.readthedocs.io/en/users/config_file.html or a redirection to the tutorial.

To me, the redirection for the configuration is excessively implicit at the moment

**Comment by satra** [comment]
i've setup a redirect at readthedocs i don't know when it will be activated.

**Comment by satra** [comment]
should be ok for some settings now. please reopen if you see other situations where this doesn't work.

**Comment by effigies** [comment]
Cool, thanks.
