### ISSUE TITLE
when outfile specific in workflow it gets recomputed each time

### ISSUE THREAD

**Issue by satra** [nipy/nipype#351]
On Thu, Apr 5, 2012 at 6:40 PM, sharad sikka <ssikka25@gmail.com> wrote:
Hi Satra,

1) Normally in my pipeline, I dont specify out_file for any node/interface  and let nipype generate out_file names for me(then i use regex to change the names of the files to the desired name). When I run the same workflow 2nd time , nipype does not recalculate any steps, it just collects outputs.

2) On the other hand if i specify out_file for interfaces, it recomputes each step in the workflow instead of just collecting the outputs. It might be because nipype might not use out_file names that user provides at the time it creates hash.

3) Also I can only specify a fixed location of the out_file with os.path.abspath. How Can I specify that it is store inside the Nipype cache directory, inside the node that ran it(similar to way we have it when temporary names are generated.)

4) Is there anyway to get around this?(workflow not having to recompute the node which has out_file defined, on a rerun)

I think if there is a workaround then the behavior would be consistent with/without specification of out_files (I may well be equally incorrect in my understanding)

Thanks in advance!
sharad

**Comment by alvaroabascar** [comment]
I've stumbled against this issue when specifying the outfiles.

I did this because I was running the same workflow on different data in a multi-threaded way. Since all the threads from a single process share the same directory, multithreading wouldn't work without specifying all the outfiles as absolute paths (otherwise the threads go crazy and start looking for the files in the wrong directories).

Is any way to surpass this issue? or any way to run things in several threads that I am missing? This is a real problem.

**Comment by effigies** [comment]
> is there a particular reason you need to specify outfile in a workflow?

FWIW, my use in #1411 was mostly to be able to set an extension (`.nii` instead of `.nii.gz`) and set a name that would end up in a Sinker, avoiding the otherwise necessary `Gunzip` and `Rename` nodes.

**Comment by satra** [comment]
i feel if the interfaces have `hash_files=False`, this becomes a non-issue.
