### ISSUE TITLE
Please consider making nipype compatible with traits >= 6.4

### ISSUE THREAD

**Issue by penguinpee** [nipy/nipype#3661]
I'm aware that traits 6.4.0 introduced breaking changes and that for that reason the version is pinned to `<6.4` (#3501). I'm also aware that there are [currently no plans](https://github.com/nipy/nipype/issues/3536#issuecomment-1406789730) to overhaul nipype.

However, something will break eventually, e.g with a newer Python release, requiring adaption to a newer traits version. Since current supported Fedora releases have all updated traits to `>6.4`, it's preventing me from packaging nipype for Fedora.

I'm not sure it's within my capabilities to help refactoring (probably not). But is there some documentation, ongoing work or similar, which would allow me to get an idea what needs changing where and what possible culprits may be?

So far, I've seen a single test out of the 2000+ tests failing due to the newer traits version. That's running tests without optional dependencies, which may hide a few additional failures.

**Comment by a-detiste** [comment]
same pain on Debian

**Comment by effigies** [comment]
Sorry, I thought I had responded to this, but it was probably in some tab that got closed.

When traits 6.4 came out, we saw many more than 1 test fail, so it's possible that they've re-added compatibility shims that would make the process less daunting. If you have a PR to resolve the issue, I'd be willing to review it and get it in.

One caution: Nipype has severe technical debt, most notably in the CI infrastructure. There is very little appetite to spend time on this project, not least because getting it back up to being properly tested would be a massive time sink. I'd be willing to onboard new maintainers, if you've got the interest and time.
