### ISSUE TITLE
Regression testing on tutorials

### ISSUE THREAD

**Issue by chrisfilo** [nipy/nipype#7]
Add some regression testing on our tutorials so we're sure they continue to work.

**Comment by physicsdaniel** [comment]
Hi @chrisfilo , 
I stumbled upon an erroneous tutorial, so I thought pointing it out here would be a good idea.

I am new to nipype and looked first at the [tutorial by mwaskom](https://github.com/mwaskom/nipype_concepts) because it was the first link concerning nipype tutorials on [readthedocs](http://nipype.readthedocs.io/en/latest/quickstart.html). After talking to @mwaskom about a few issues I found with the 2-year-old tutorial, he pointed me at @miykael 's [tutorial](https://miykael.github.io/nipype_tutorial/) as a better/newer one. 

After that, I figured it would be good to post somewhere, that there is an issue with the very first tutorial that is linked at the main nipype documentation... and here I am.

**Comment by mgxd** [comment]
@dafrose thanks for the feedback - it can be hard to maintain these tutorials as nipype and its dependencies are rapidly changing! If you have fixed the issues in your fork, perhaps you can submit a PR so others who want to learn nipype won't run into all these errors

**Comment by satra** [comment]
also we are planning on completely replacing these tutorials with these excellent ones from @miykael : https://miykael.github.io/nipype_tutorial/

**Comment by djarecka** [comment]
@dafrose - thanks for feedback! The tutorial has been updated, please consider creating a new issue in the nipype_tutorail repo (https://github.com/miykael/nipype_tutorial/issues) if you find anything that is not working. 

@miykael and I will work on moving the user guide part of the nipype doc to the nipype_tutorial.

**Comment by dafrose** [comment]
wow, cool! I'm sorry I didn't submit a pull request myself. I hadn't fixed it all and lost track of it when moving on to other stuff. All the more happy, that it has been solved now. Thank you very much!

**Comment by djarecka** [comment]
simple tests will be added to nipype tutorial in [this pr](https://github.com/miykael/nipype_tutorial/pull/39).

I'm closing this issue now, please add comments or open new issue in the nipype_tutorial repo
